<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseTermHasTags extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('term_has_tags');
        $this->hasColumn('term_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('tag_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('quote_identifier', true);
        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('Term', array(
             'local' => 'term_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Tag', array(
             'local' => 'tag_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}