<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseTemplate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('template');
        $this->hasColumn('name', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '10',
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('quote_identifier', true);
        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasMany('Page', array(
             'local' => 'id',
             'foreign' => 'template_id'));
    }
}