<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasePageHasSlots extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('page_has_slots');
        $this->hasColumn('page_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('slot_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('quote_identifier', true);
        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('Page', array(
             'local' => 'page_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Slot', array(
             'local' => 'slot_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}