<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseSlot extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('slot');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('position', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '100',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('content', 'string', 100000, array(
             'type' => 'string',
             'length' => '100000',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('quote_identifier', true);
        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasMany('PageHasSlots', array(
             'local' => 'id',
             'foreign' => 'slot_id'));
    }
}