<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/05/31 22:26:10

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=db369392464.db.1and1.com;dbname=db369392464',
  'username' => 'dbo369392464',
  'password' => 'qweASD123',
  'name' => 'doctrine',
)),);
