<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/06/28 11:08:33

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=wiki',
  'username' => 'root',
  'password' => 'n@ma',
  'name' => 'doctrine',
)),);
