<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TermTable extends Doctrine_Table
{

  public function getTerm($term)
  {
    $results = $this->createQuery('t')
          ->where('t.word = ?', $term)
          ->addWhere('t.approved = ?', true)
          ->orderBy('t.likes desc')
          ->execute();

    return $results;
  }

  public function getTerms4Slider()
  {

    $terms = $this->createQuery('t')
           ->orderBy('t.word ASC')
           ->execute();

    return $terms;
  }

  public function getSlideFromWord($word)
  {
    $terms = $this->getTerms4Slider();

    foreach($terms as $key=>$term)
    {
      if($term->getWord() == $word)
      {
        $result = $key;
      }
      $key++;
    }
    return intval($result/28) +1;
    
  }
  
}