default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [skin.css, main.css]

  javascripts:    [jquery-1.5.2-min.js, jquery.jcarousel.js, main.js]

  has_layout:     on
  layout:         layout
