<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/05/31 22:26:55

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=wiki',
  'username' => 'root',
  'password' => 'n@ma',
  'name' => 'doctrine',
)),);
