<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/06/28 11:08:17
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
