<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/05/31 23:40:30
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
